name: Bug Report
description: 'Something is not working.'
title: '[Bug]: '
assignees:
  - Fyoncle
labels:
  - bug
body:
  - type: dropdown
    id: loader
    attributes:
      label: Loader
      description: Which loader are you using?
      options:
        - Datapack
        - Fabric
        - Forge
        - Quilt
        - NeoForge
    validations:
      required: true
  - type: input
    id: minecraft
    attributes:
      label: Minecraft Version
      description: Which Minecraft version are you playing on?
      placeholder: 1.20.1
    validations:
      required: true
  - type: input
    id: sa_version
    attributes:
      label: Spawn Animations version
      description: >-
        Which version of Spawn Animations are you using?
      placeholder: v1.10
    validations:
      required: true
  - type: input
    id: sa_compats_version
    attributes:
      label: Spawn Animations Compats version
      description: >-
        Which version of Spawn Animations Compats are you using?
      placeholder: v1.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear explanation of the bug.
      placeholder: >-
        Version v1.x not working on Minecraft 1.xx.x
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: >-
        Required steps to reproduce the bug.
      placeholder: |
        1. Install Spawn Animations & Spawn Animations Compats on Minecraft 1.xx.x
        2. Join a world
        3. See this mod stated as compatible is not working on this version
  - type: input
    id: logs
    attributes:
      label: Relevant logs
      description: |
        Please upload the log file to [mclo.gs](https://mclo.gs/) and paste the given url here.  
      placeholder: https://mclo.gs/...
